References in Nuxt setup
feature-sliced/steiger pull request #117
Opened 2024-10-29 12:41 UTC by daniilsapa

Resolves #94 

@illright 
The cause of the issue was not exactly in the Nuxt setup. The problem was that `compilerOption.paths` specified in config extensions (`"extends": "./.nuxt/tsconfig.json"`) were not resolved and thus path aliases like `@/`, `~/` didn't work. 

So such paths from extensions were applied to the FSD root.
```js
 {
     "~": [
        ".."
      ],
      "~/*": [
        "../*"
      ],
      "@": [
        ".."
      ],
      "@/*": [
        "../*"
      ],
}
```

I made changes to transform such paths from `../*` to `/*` and then apply them to the root.

Nuxt setup extends a default config from the `.nuxt` folder it helped us to uncover this issue.

Sorry for the delay!

2024-10-29 22:04 UTC, illright requested changes
Could you also resolve the conflicts? Recently there's been a change to that file which did a similar thing, I wonder if your changes overlap with it or not

2024-10-29 22:04 UTC, illright commented on packages/steiger-plugin-fsd/src/insignificant-slice/index.ts
> +      return [key, values.map((value: string) => join(configPath, '..', value))]
issue: the `'..'` part looks hard-coded for the Nuxt case. I don't fully understand how this function works and how it fixes the issue

2024-10-30 10:54 UTC, daniilsapa commented
Got it, yes, let me resolve the conflicts first. Then I'll fix the function and also now I see some other flaws of my solution

2024-11-06 09:17 UTC, illright commented on packages/steiger-plugin-fsd/src/insignificant-slice/index.ts
suggestion: the dependency resolution is also used in several other rules, it needs to be updated there as well, I think

2024-11-06 11:14 UTC, daniilsapa commented on packages/steiger-plugin-fsd/src/insignificant-slice/index.ts
Yep, made the needed changes

2024-11-11 16:41 UTC, daniilsapa commented
@illright 

I fixed the first issue that we discussed in the morning by always transforming `compilerOptions.paths` to absolute, so now we're not afraid of losing context what Steiger is launched from the folder other than the one where the initial tsconfig is put.

Regarding the 2nd problem

https://stackblitz.com/edit/nuxt-starter-ap1c4y?file=README.md

**How to reproduce**

When `/src/features/session/logout/index` has **.js** extension. It reports this diagnostic, from which we can see that the file is noticed by the tool.
<img width="1159" alt="Screenshot 2024-11-11 at 18 29 00" src="https://github.com/user-attachments/assets/ce1c4115-5b52-407f-a518-34397c39ed30">


When `/src/features/session/logout/index` has **.vue** extension. It reports the following diagnostic, from which we can see that the tool does not see that the file is imported in other files.
<img width="1135" alt="Screenshot 2024-11-11 at 18 29 44" src="https://github.com/user-attachments/assets/631dcb52-ab3b-4835-b652-c135e8f10b42">

Don't forget to wrap/unwrap the code inside `/src/features/session/logout/index` with `<script></script>` when changing extensions 


You can temporarily change fileExists, directoryExists parameters from these:

<img width="772" alt="Screenshot 2024-11-11 at 18 38 27" src="https://github.com/user-attachments/assets/e37cfd27-45f1-4d72-89b3-dafbadb9b14a">
to these
<img width="764" alt="Screenshot 2024-11-11 at 18 37 45" src="https://github.com/user-attachments/assets/789ce2f0-1672-46da-9de0-3861ef45bb3a">
(I made that change locally for insignificant-slice)

Then you'll be able to see how it goes through different possible options (like `.../logout.ts`, `.../logout.js`, `.../logout/index.ts`, `.../logout/index.js`, etc) and then fails when runs out of further options

2024-11-11 16:50 UTC, daniilsapa commented
resolveDependency from `.../steiger-plugin-fsd/src/_lib/resolve-dependency.ts` uses resolveImport from `@feature-sliced/filesystem`. It looks like we need to add some wrapper in resolveImport to add .vue extension case. Also, maybe we need to create space to gracefully add more custom extensions, but I'm not sure it's inside the score of the task, we can create a quick fix and an issue to design and implement a module responsible for custom extensions

2024-11-11 19:55 UTC, illright approved these changes

2024-11-11 20:17 UTC, illright approved these changes

2024-11-11 20:21 UTC, merged