Added support of the steiger config for windows
feature-sliced/steiger pull request #134
Opened 2024-11-27 23:15 UTC by mx-ryabov

Hey! 
My version of tests looks a bit overwhelming, I also thought about a simple function that would take a platform parameter and depending on the value would prepend `C`:, but I'm not sure if that's the right way to do tests. However, if you think otherwise, I can rework it (or am open to any other suggestions)

2024-12-01 13:56 UTC, illright requested changes
Thanks for making a PR! Sorry it took a while to get a review. The solution looks solid. The tests are a bit hard to parse, I think we can make them simpler by simply writing two `it`s and then skipping one or the other based on the platform. Our CI runs in both OSes, so we will cover everything that way

For reference: https://vitest.dev/api/#test-runif

2024-12-01 13:56 UTC, illright commented on .changeset/early-stingrays-appear.md
> +Added support of the steiger config for windows
suggestion: the support is already there, it's just buggy :)


```suggestion
Fix drive label handling in paths on Windows 
```

2024-12-01 13:56 UTC, illright commented on .changeset/early-stingrays-appear.md
> +'steiger': minor
Also I think it should be a patch change, since it's a bug fix:
```suggestion
'steiger': patch 
```

2024-12-01 18:33 UTC, mx-ryabov commented
I considered a similar to yours approach but I thought about the case when somebody on a unix machine could break something for windows and this developer won't find out it until the CI checks passed.
But anyway all your comments are resolved, let me know if you need something else. Thank you!

2024-12-02 14:49 UTC, illright approved these changes
Thanks for addressing the comments! Nothing else on my side, great job, let's merge.

As for your concern about devs not finding out until CI — there's a lot of places where that can happen, and that's okay, that's why we have CI on several OSes, to alert devs that something might not work on someone else's machine

2024-12-02 14:51 UTC, merged